// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mindspheresinglesignon.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import mindspheresinglesignon.proxies.MindSphereToken;
import mindspheresinglesignon.proxies.microflows.Microflows;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class MindSphereAccessTokenConnector extends CustomJavaAction<IMendixObject>
{
	public MindSphereAccessTokenConnector(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		MindSphereToken accessToken = Microflows.dS_MindSphereAccessToken(context());
		
		if (accessToken == null) {
			return null;
		}
		
		return accessToken.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "MindSphereAccessTokenConnector";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
