// This file was generated by Mendix Modeler 7.23.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mindsphereosbarconnector.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the MindSphereOSBarConnector module

	public static java.lang.String getConfig()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("MindSphereOSBarConnector.Config");
	}
}