// This file was generated by Mendix Modeler 7.23.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mindspheresinglesignon.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the MindSphereSingleSignOn module

	public static boolean getAskForCredentialsOnStartup()
	{
		return (java.lang.Boolean)Core.getConfiguration().getConstantValue("MindSphereSingleSignOn.AskForCredentialsOnStartup");
	}

	/**
	* Name of the application used in the Developer Cockpit.
	* 
	* This is used for JWT validation process and is mapped to the "aud" claim.
	*/
	public static java.lang.String getCockpitApplicationName()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("MindSphereSingleSignOn.CockpitApplicationName");
	}

	/**
	* Used to get application credentials, must be identical to the version in the developer cockpit.
	*/
	public static java.lang.String getCockpitApplicationVersion()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("MindSphereSingleSignOn.CockpitApplicationVersion");
	}

	/**
	* If the value is 'true' the MindSphere Application Credentials' will be used, otherwise the 'Service Credentials' will be used to fetch a MindSphere token for local development.
	* 
	* NOTE: Service Credentials are deprecated and should only be used if Application Credentials are not possible.
	*/
	public static boolean getCredentialsType()
	{
		return (java.lang.Boolean)Core.getConfiguration().getConstantValue("MindSphereSingleSignOn.CredentialsType");
	}

	public static boolean getEnableLocalMindSphereApiReverseProxy()
	{
		return (java.lang.Boolean)Core.getConfiguration().getConstantValue("MindSphereSingleSignOn.EnableLocalMindSphereApiReverseProxy");
	}

	/**
	* Name of Tenant where application is hosted.
	* Name is used during retrieval of application credentials.
	*/
	public static java.lang.String getHostTenant()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("MindSphereSingleSignOn.HostTenant");
	}

	/**
	* The Mindsphere Gateway URL
	*/
	public static java.lang.String getMindSphereGatewayURL()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("MindSphereSingleSignOn.MindSphereGatewayURL");
	}

	/**
	* MindSphereSingleSignOn
	*/
	public static java.lang.String getModuleName()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("MindSphereSingleSignOn.ModuleName");
	}

	/**
	* Endpoint where to fetcht the public keys for token validation.
	*/
	public static java.lang.String getPublicKeyURL()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("MindSphereSingleSignOn.PublicKeyURL");
	}

	/**
	* Used in get application credentials.
	*/
	public static java.lang.String getUserTenant()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("MindSphereSingleSignOn.UserTenant");
	}
}