// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mindspheresinglesignon.proxies;

public class TenantObject
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject tenantObjectMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MindSphereSingleSignOn.TenantObject";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		TenantObject_Tenant("MindSphereSingleSignOn.TenantObject_Tenant");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public TenantObject(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MindSphereSingleSignOn.TenantObject"));
	}

	protected TenantObject(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject tenantObjectMendixObject)
	{
		if (tenantObjectMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MindSphereSingleSignOn.TenantObject", tenantObjectMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MindSphereSingleSignOn.TenantObject");

		this.tenantObjectMendixObject = tenantObjectMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'TenantObject.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static mindspheresinglesignon.proxies.TenantObject initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return mindspheresinglesignon.proxies.TenantObject.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static mindspheresinglesignon.proxies.TenantObject initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		if (com.mendix.core.Core.isSubClassOf("MindSphereSingleSignOn.TokenForScheduledEvents", mendixObject.getType()))
			return mindspheresinglesignon.proxies.TokenForScheduledEvents.initialize(context, mendixObject);

		return new mindspheresinglesignon.proxies.TenantObject(context, mendixObject);
	}

	public static mindspheresinglesignon.proxies.TenantObject load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return mindspheresinglesignon.proxies.TenantObject.initialize(context, mendixObject);
	}

	public static java.util.List<? extends mindspheresinglesignon.proxies.TenantObject> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<mindspheresinglesignon.proxies.TenantObject> result = new java.util.ArrayList<mindspheresinglesignon.proxies.TenantObject>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MindSphereSingleSignOn.TenantObject" + xpathConstraint))
			result.add(mindspheresinglesignon.proxies.TenantObject.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of TenantObject_Tenant
	 */
	public final mindspheresinglesignon.proxies.Tenant getTenantObject_Tenant() throws com.mendix.core.CoreException
	{
		return getTenantObject_Tenant(getContext());
	}

	/**
	 * @param context
	 * @return value of TenantObject_Tenant
	 */
	public final mindspheresinglesignon.proxies.Tenant getTenantObject_Tenant(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mindspheresinglesignon.proxies.Tenant result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TenantObject_Tenant.toString());
		if (identifier != null)
			result = mindspheresinglesignon.proxies.Tenant.load(context, identifier);
		return result;
	}

	/**
	 * Set value of TenantObject_Tenant
	 * @param tenantobject_tenant
	 */
	public final void setTenantObject_Tenant(mindspheresinglesignon.proxies.Tenant tenantobject_tenant)
	{
		setTenantObject_Tenant(getContext(), tenantobject_tenant);
	}

	/**
	 * Set value of TenantObject_Tenant
	 * @param context
	 * @param tenantobject_tenant
	 */
	public final void setTenantObject_Tenant(com.mendix.systemwideinterfaces.core.IContext context, mindspheresinglesignon.proxies.Tenant tenantobject_tenant)
	{
		if (tenantobject_tenant == null)
			getMendixObject().setValue(context, MemberNames.TenantObject_Tenant.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.TenantObject_Tenant.toString(), tenantobject_tenant.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return tenantObjectMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mindspheresinglesignon.proxies.TenantObject that = (mindspheresinglesignon.proxies.TenantObject) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MindSphereSingleSignOn.TenantObject";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
