// This file was generated by Mendix Modeler 7.23.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mindspheresinglesignon.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the MindSphereSingleSignOn module
	public static mindspheresinglesignon.proxies.CredentialsResponse aCT_ApplicationCredentials(IContext context, mindspheresinglesignon.proxies.Credentials _credentialsIn)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("CredentialsIn", _credentialsIn == null ? null : _credentialsIn.getMendixObject());
			IMendixObject result = (IMendixObject)Core.execute(context, "MindSphereSingleSignOn.ACT_ApplicationCredentials", params);
			return result == null ? null : mindspheresinglesignon.proxies.CredentialsResponse.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static mindspheresinglesignon.proxies.Credentials aCT_CreateCredentials(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			IMendixObject result = (IMendixObject)Core.execute(context, "MindSphereSingleSignOn.ACT_CreateCredentials", params);
			return result == null ? null : mindspheresinglesignon.proxies.Credentials.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static mindspheresinglesignon.proxies.CredentialsResponse aCT_ServiceCredentials(IContext context, mindspheresinglesignon.proxies.Credentials _credentialsIn)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("CredentialsIn", _credentialsIn == null ? null : _credentialsIn.getMendixObject());
			IMendixObject result = (IMendixObject)Core.execute(context, "MindSphereSingleSignOn.ACT_ServiceCredentials", params);
			return result == null ? null : mindspheresinglesignon.proxies.CredentialsResponse.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static boolean bC_AddTenantAssociation(IContext context, mindspheresinglesignon.proxies.TenantObject _tenantObject)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("TenantObject", _tenantObject == null ? null : _tenantObject.getMendixObject());
			return (java.lang.Boolean)Core.execute(context, "MindSphereSingleSignOn.BC_AddTenantAssociation", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static mindspheresinglesignon.proxies.TokenForScheduledEvents dS_GetAccessTokenForScheduledEvents(IContext context, mindspheresinglesignon.proxies.Tenant _tenant)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Tenant", _tenant == null ? null : _tenant.getMendixObject());
			IMendixObject result = (IMendixObject)Core.execute(context, "MindSphereSingleSignOn.DS_GetAccessTokenForScheduledEvents", params);
			return result == null ? null : mindspheresinglesignon.proxies.TokenForScheduledEvents.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static mindspheresinglesignon.proxies.MindSphereToken dS_MindSphereAccessToken(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			IMendixObject result = (IMendixObject)Core.execute(context, "MindSphereSingleSignOn.DS_MindSphereAccessToken", params);
			return result == null ? null : mindspheresinglesignon.proxies.MindSphereToken.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static mindspheresinglesignon.proxies.MindSphereAccount dS_MindSphereAccount(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			IMendixObject result = (IMendixObject)Core.execute(context, "MindSphereSingleSignOn.DS_MindSphereAccount", params);
			return result == null ? null : mindspheresinglesignon.proxies.MindSphereAccount.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static java.lang.String gET_PublicKeys(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			return (java.lang.String)Core.execute(context, "MindSphereSingleSignOn.GET_PublicKeys", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static boolean registerSingleSignOn(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			return (java.lang.Boolean)Core.execute(context, "MindSphereSingleSignOn.RegisterSingleSignOn", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}